# --------------- DÉBUT COUCHE OS -------------------
FROM debian:stable-slim
# --------------- FIN COUCHE OS ---------------------

# ------- MÉTADONNÉES DE L'IMAGE --------------------
LABEL version="1.0" maintainer="Mike <mike37510@gmail.com>"


# --------------- UPDATE ----------------------------
RUN apt-get update -y && \
    apt-get upgrade
# --------------- FIN UPDATE ------------------------

# --------------- INSTALL NANO ----------------------
RUN apt-get install nano -y
# --------------- FIN INSTALL NANO-------------------

# ------------ INSTALL OPEN SSH ---------------------
RUN apt-get install openssh-server -y && \
    apt-get install wget -y && \
    wget https://raw.githubusercontent.com/mike37510/mescontainers/main/docker/debian-custom/sshd_config &&\
    mv sshd_config /etc/ssh

CMD systemctl enable ssh && \
    service ssh start
# --------- FIN INSTALL OPEN SSH -------------------